<?php

header('Content-Type: text/plain');

include('synch.php');

$SPRITES = 4;

$db = new PDO('sqlite:crests.db');

readfile('soccer.css');

print("\n/* GENERATED BY SOCCERBOT: ".gmdate('d M Y H:i:s')." */\n\n");

for ($i = 1; $i <= $SPRITES; $i++) {
  printBlock($i);
}

function printBlock($sprite) {
  global $db;

  $query = $db->query("SELECT * FROM teams WHERE sprite=".$sprite." ORDER BY sort");

  $pos = -21;
  while ($row = $query->fetch()) {
    $flair = $row['flair'];
    print('.flair-'.$flair);
    if ($row['site'] != '' || $row['twitter'] != '') {
      print(',.linkflair-'.$flair.' .linkflairlabel');
    }
    print('{background-position:0 '.$pos.'px}'."\n");
    $pos -= 21;
  }
}
?>
