<?php

header('Content-Type: text/plain');

include('synch.php');

readfile('soccer.css');

$db = new PDO('sqlite:crests.db');

print("\n/* GENERATED BY SOCCERBOT: ".gmdate('d M Y H:i:s')." */\n\n");
printBlock(1);
printBlock(2);
printBlock(3);

function printBlock($sprite) {
  global $db;

  $query = $db->query("SELECT * FROM teams WHERE sprite=".$sprite." ORDER BY sort");

  $pos = -21;
  while ($row = $query->fetch()) {
    $extended = false;
    print('.flair-'.$row['flair']);
    if ($row['site'] != '') {
      print(','.'a[href*="'.$row['site'].'"]:before');
      $extended = TRUE;
    }
    if ($row['twitter'] != '' && $row['ignore'] != 'x') {
      print(','.'a[href*="/'.$row['twitter'].'/"]:before');
      $extended = TRUE;
    }
    //if ($row['wikipedia'] != '') {
    //  print(','.'a[href$="/'.$row['wikipedia'].'"]:before');
    //  $extended = TRUE;
    //}
    if ($extended && $sprite != 1) {
      print('{background:url(%%s'.$sprite.'%%) 0 '.$pos.'px');
    } else {
      print('{background-position:0 '.$pos.'px');
    }
    if ($extended) {
      print(';content:""');
    }
    print("}\n");
    $pos -= 21;
  }
}
?>
