<?php

header('Content-Type: text/plain');

include('synch.php');

readfile('soccerbot.css');

$db = new PDO('sqlite:crests.db');

print("\n/* GENERATED BY SOCCERBOT: ".gmdate('d M Y H:i:s')." */\n\n");
printBlock(1);
printBlock(2);
printBlock(3);

function printBlock($sprite) {
  global $db;

  $query = $db->query("SELECT * FROM teams WHERE sprite=".$sprite." ORDER BY sort");

  $pos = -21;
  while ($row = $query->fetch()) {
    print('a[href$="='.$row['flair'].'"]:before{background-position:0 '.$pos.'px}'."\n");
    $pos -= 21;
  }
}
?>
