<?php

header('Content-Type: text/plain');

include('synch.php');

$SPRITES = 4;

$db = new PDO('sqlite:crests.db');

readfile('soccerbot.css');

print("\n/* GENERATED BY SOCCERBOT: ".gmdate('d M Y H:i:s')." */\n\n");

for ($i = 1; $i <= $SPRITES; $i++) {
  printBlock($i);
}

function printBlock($sprite) {
  global $db;

  $query = $db->query("SELECT * FROM teams WHERE sprite=".$sprite." ORDER BY sort");

  $pos = -21;
  while ($row = $query->fetch()) {
    print('a[href$="='.$row['flair'].'"]:before{background-position:0 '.$pos.'px}'."\n");
    $pos -= 21;
  }
}
?>
